# Generated by Django 5.0.7 on 2024-08-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_deadline',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='Instructor', max_length=64),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
