# Generated by Django 5.1 on 2024-08-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_lesson_options_rename_title_lesson_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='text',
        ),
    ]
